### ISSUE TITLE
CST and MO-Net

### ISSUE THREAD

**Issue by prometx11** [EndyWon/StyleEval#1]
Hi,
thank you very much for sharing the code for this interesting paper.
as far as I understand this is just the evaluation method, so basically the first contribution of the paper but not the second one with the CST and MO-Net right? 

If thats the case, are you also going to publish the code for CST and MO-Net? 

Thank you for clarifying. 
Best regards

**Comment by EndyWon** [comment]
Thanks for the interest in our paper. Yes, the current released code is only the evaluation method. We will publish the code of MO-Net as soon as possible. In terms of CST, you can write simple script according to the Algorithm 1 in our paper.

**Comment by prometx11** [comment]
Thanks for replying!
I am looking forward to the MO-Net and in the meantime will try to script the CST. 
I have been playing with a lot of neural style transfer algos, but most of them just introduce too much noise/artefacts, so your approach looks really interesting to me.

**Comment by EndyWon** [comment]
The code of MO-Net has been uploaded. Good luck!

**Comment by prometx11** [comment]
@EndyWon Thank you very much for the code.
There might be a problem with certain style images.
Sometimes, styling just stops after 20-60 iterations and the styled image has just some artifacts. 
Have you observed this problem as well in your tests and maybe found a solution?

**Comment by EndyWon** [comment]
@prometx11 This problem may be caused by the fact that the gradients of loss tuned by our automatic parameter-tuning module are too low for L-BFGS optimizer. Increasing the magnitude of loss values or weighting each loss by hand may address this problem (modify the code in Line 229-242 in MONet.py). Best!
